[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ai4h_databank"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "buster @ git+https://github.com/jerpint/buster",
    "gradio",
    "huggingface-hub",
    "pymongo"
]

[project.optional-dependencies]
tests = [
    "pytest"
]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
addopts = [
    "--import-mode=importlib",
]
