name: staging-ci

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
  tests:
    runs-on: ubuntu-latest
    steps:
      # Other steps specific to the dev stage
      - name: Run Unit Tests
        uses: ./.github/workflows/unit_tests.yml

      - name: unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          INSTANCE_TYPE: test
          INSTANCE_NAME: github-actions
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -U jinja2
          pip install -r requirements.txt
          pip install -e .[tests]
          pytest --ignore=performance
  deploy-staging-hf-space:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub
          sh scripts/deploy_hf_space.sh staging
