name: dev-ci

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 120"
      - name: isort
        run: |
          pip install isort
          isort --profile black --check-only .
      - name: unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .[tests]
          pytest
      - name: Update summary
        run: cat results_summary.md >> $GITHUB_STEP_SUMMARY
  deploy-dev:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_DEV_SERVER }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
