name: dev-ci

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Other steps specific to the dev stage
      - name: Run Unit Tests
        uses: ./.github/workflows/unit_tests.yml

  deploy-dev-heroku:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_DEV_SERVER }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
  deploy-dev-hf-space:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub
          sh scripts/deploy_hf_space.sh dev
