name: prod-ci

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 120"
      - name: isort
        run: |
          pip install isort
          isort --profile black --check-only .
      - name: unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
          AI4H_MONGODB_USERNAME: ${{ secrets.AI4H_MONGODB_USERNAME }}
          AI4H_MONGODB_PASSWORD: ${{ secrets.AI4H_MONGODB_PASSWORD }}
          AI4H_MONGODB_CLUSTER: ${{ secrets.AI4H_MONGODB_CLUSTER }}
          AI4H_MONGODB_DB_DATA: ${{ vars.AI4H_MONGODB_DB_DATA }}
          AI4H_MONGODB_DB_LOGGING: ${{ vars.AI4H_MONGODB_DB_LOGGING }}
          AI4H_PINECONE_API_KEY: ${{ secrets.AI4H_PINECONE_API_KEY }}
          AI4H_PINECONE_ENV: ${{ secrets.AI4H_PINECONE_ENV }}
          AI4H_PINECONE_INDEX: ${{ vars.AI4H_PINECONE_INDEX }}
          AI4H_PINECONE_NAMESPACE: ${{ vars.AI4H_PINECONE_NAMESPACE }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .[tests]
          pytest --ignore=performance
  deploy-prod:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_PROD_SERVER }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
