name: staging-ci

on: workflow_dispatch

jobs:
  tests:
    uses: Mila-AI4H/ai4h_databank/.github/workflows/unit_tests.yaml@ci-dependencies
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

  deploy-staging-hf-space:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub
          sh scripts/deploy_hf_space.sh staging
