name: prod-ci

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 120"
      - name: isort
        run: |
          pip install isort
          isort --profile black --check-only .
      - name: unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
          INSTANCE_TYPE: "dev"
          INSTANCE_NAME: "github-actions"
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .[tests]
          pytest --ignore=performance
  deploy-prod-heroku:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_PROD_SERVER }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
  deploy-prod-hf-space:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy to huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          python3 -m pip install --upgrade pip
          pip install huggingface_hub
          sh scripts/deploy_hf_space.sh prod
