# cat .github/workflows/deploy.yml
name: deploy-dev
on: [push, pull_request]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml  # use the callable tests job to run tests
  deploy:
    name: deploy-dev-env
    needs: [tests]  # require tests to pass before deploy runs
    uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: ${{secrets.HEROKU_DEV_SERVER}}
      heroku_email: ${{secrets.HEROKU_EMAIL}}