name: performance

on: 
  workflow_dispatch:
    inputs:
      n_sources:
        description: "Number of sources to use"
        required: true
        default: 3
        type: number
      validate_documents:
        description: "Validate documents using GPT"
        required: true
        default: false
        type: boolean
      hybrid_retrieval:
        description: "Use hybrid retrieval"
        required: true
        default: false
        type: boolean
jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: performance
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          INSTANCE_TYPE: dev
          INSTANCE_NAME: github-actions
          N_SOURCES: ${{ github.event.inputs.n_sources }}
          VALIDATE_DOCUMENTS: ${{ github.event.inputs.validate_documents }}
          HYBRID_RETRIEVAL: ${{ github.event.inputs.hybrid_retrieval }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[tests]
          pytest --run_expensive --ignore=tests
      - name: Save performance results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            results_detailed.csv
            results_summary.csv
      - name: Update summary
        run: cat results_summary.md >> $GITHUB_STEP_SUMMARY
