name: performance

on: workflow_dispatch

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: performance
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
          AI4H_MONGODB_USERNAME: ${{ secrets.AI4H_MONGODB_USERNAME }}
          AI4H_MONGODB_PASSWORD: ${{ secrets.AI4H_MONGODB_PASSWORD }}
          AI4H_MONGODB_CLUSTER: ${{ secrets.AI4H_MONGODB_CLUSTER }}
          AI4H_MONGODB_DB_DATA: ${{ vars.AI4H_MONGODB_DB_DATA }}
          AI4H_PINECONE_API_KEY: ${{ secrets.AI4H_PINECONE_API_KEY }}
          AI4H_PINECONE_ENV: ${{ secrets.AI4H_PINECONE_ENV }}
          AI4H_PINECONE_INDEX: ${{ vars.AI4H_PINECONE_INDEX }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .[tests]
          pytest --run_expensive --ignore=tests
      - name: Save performance results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            results_detailed.csv
            results_summary.csv
      - name: Update summary
        run: cat results_summary.md >> $GITHUB_STEP_SUMMARY
