name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 120"
      - name: isort
        run: |
          pip install isort
          isort --profile black --check-only .
      # TODO: Add some unit tests
      # - name: unit tests
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pytest
      # This is so that the heroku secrets get saved encrypted on the docker image
      - name: install Pass
        run: apt-get install pass -y && echo '{"credsStore":"pass"}' >> ~/.docker/config.json
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
