jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 120"
      - name: isort
        run: |
          pip install isort
          isort --profile black --check-only .
      - name: unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          INSTANCE_TYPE: test
          INSTANCE_NAME: github-actions
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          python3 -m pip install --upgrade pip
          pip install -U jinja2
          pip install -r requirements.txt
          pip install -e .[tests]
          pytest --ignore=performance
